services:

  server:
    build: ./server
    ports:
      - "8080:8080"
    command: npm run start

  client_mobile:
    build: ./client_mobile
    volumes:
      - common_volume.yaml
    command: npm run start

  client_web:
    build: ./client_web
    ports:
      - "8081:8081"
    volumes:
      - common_volume.yaml
    command: npm run start
    depends_on:
      - server
      - client_mobile
    
